// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgDrxnXW9w3chbMDkzlr_30jv5KCt1iSo',
    appId: '1:116702571332:web:07bd499e8bd5f48cf68511',
    messagingSenderId: '116702571332',
    projectId: 'projectoed-9c853',
    authDomain: 'projectoed-9c853.firebaseapp.com',
    storageBucket: 'projectoed-9c853.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb7LL2tW-MBn0Run_O9fv3WDTJgoD5kio',
    appId: '1:116702571332:android:d7c20746f925fbc6f68511',
    messagingSenderId: '116702571332',
    projectId: 'projectoed-9c853',
    storageBucket: 'projectoed-9c853.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpwxyy-agl49zo4KQPFxcd85uhfInnJKM',
    appId: '1:116702571332:ios:f496be28e27bea21f68511',
    messagingSenderId: '116702571332',
    projectId: 'projectoed-9c853',
    storageBucket: 'projectoed-9c853.firebasestorage.app',
    iosBundleId: 'com.example.projectoed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgDrxnXW9w3chbMDkzlr_30jv5KCt1iSo',
    appId: '1:116702571332:web:ae4b3962e8537007f68511',
    messagingSenderId: '116702571332',
    projectId: 'projectoed-9c853',
    authDomain: 'projectoed-9c853.firebaseapp.com',
    storageBucket: 'projectoed-9c853.firebasestorage.app',
  );
}
